# Puerto en que escucha Spring Boot
server.port=8080

# Servicio de la base de datos PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# URL de conexion: Apuntando a la IP publica de tu instancia Debian y al puerto externo 2345
spring.datasource.url=jdbc:postgresql://${DB_HOST:52.7.62.14}:${DB_PORT:2345}/${DB_NAME:gobierno_mmz}

# Credenciales
spring.datasource.username=${DB_USER:aaee_gobierno}
spring.datasource.password=${DB_PASSWORD:root}

# Parametros del Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2